# Generated by Django 4.2.6 on 2023-10-13 05:35

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_chat',
            name='fullname',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='add_chat',
            name='email',
            field=models.CharField(max_length=200, unique=True, validators=[Chat.models.validate_mail]),
        ),
    ]
