# Generated by Django 4.2.6 on 2023-10-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_add_chat_fullname_alter_add_chat_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_chat',
            name='fullname',
        ),
    ]
