# Generated by Django 4.2.6 on 2023-10-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_remove_add_chat_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_chat',
            old_name='email',
            new_name='username',
        ),
    ]
