# Generated by Django 4.2.6 on 2023-10-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_alter_add_chat_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_chat',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
