# Generated by Django 4.2.6 on 2023-10-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_chat',
            name='content',
            field=models.TextField(default='null', max_length=200000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
