# Generated by Django 4.2.6 on 2023-10-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_add_chat_content_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_chat',
            name='content',
        ),
    ]
