# Generated by Django 4.2.6 on 2023-10-18 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_rename_fullname_register_table_username'),
        ('Chat', '0009_remove_add_chat_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_chat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.register_table'),
            preserve_default=False,
        ),
    ]
