# Generated by Django 4.2.6 on 2023-10-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0010_add_chat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_chat',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
