# Generated by Django 4.2.6 on 2023-10-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_rename_fullname_register_table_username'),
        ('Chat', '0011_alter_add_chat_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=20000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.add_chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.register_table')),
            ],
        ),
    ]
