# Generated by Django 4.2.6 on 2023-10-19 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0012_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='chat',
            new_name='chat_with',
        ),
        migrations.AddField(
            model_name='messages',
            name='room_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
