# Generated by Django 4.2.5 on 2023-09-22 09:45

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[App.models.validate_mail])),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
