# Generated by Django 4.2.5 on 2023-09-25 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_register_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_table',
            name='firstname',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
