# Generated by Django 4.2.5 on 2023-10-02 06:05

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_register_table_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='password',
            field=models.CharField(max_length=250, validators=[App.models.validate_password_model]),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
