# Generated by Django 4.2.5 on 2023-10-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_login_table_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_table',
            name='email',
            field=models.EmailField(max_length=300, unique=True),
        ),
    ]
