# Generated by Django 4.2.5 on 2023-10-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_register_table_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_table',
            name='email',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='firstname',
            field=models.CharField(max_length=200),
        ),
    ]
