# Generated by Django 4.2.5 on 2023-10-02 07:18

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_register_table_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='username',
            field=models.CharField(max_length=200, unique=True, validators=[App.models.validate_username_model]),
        ),
    ]
