# Generated by Django 4.2.5 on 2023-10-02 07:28

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_login_table_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_table',
            name='firstname',
            field=models.CharField(max_length=200, validators=[App.models.validate_password_model]),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='lastname',
            field=models.CharField(max_length=200, validators=[App.models.validate_password_model]),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='password',
            field=models.CharField(max_length=250, validators=[App.models.validate_password_model]),
        ),
    ]
