# Generated by Django 4.2.5 on 2023-10-05 06:04

import App.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_register_table_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='username',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]{1}[a-z_]{1,20}[0-9]{2,10}', message='Enter a correct username')]),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='firstname',
            field=models.CharField(max_length=200, validators=[App.models.validate_password_model, django.core.validators.RegexValidator('[a-z^a-z]{1,20}', message='Special characters are not allowed')]),
        ),
    ]
