# Generated by Django 4.2.5 on 2023-10-05 06:06

import App.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_login_table_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_table',
            name='firstname',
            field=models.CharField(max_length=200, validators=[App.models.validate_password_model, django.core.validators.RegexValidator('[^a-z]{1,20}', message='Special characters are not allowed')]),
        ),
    ]
