# Generated by Django 4.2.5 on 2023-10-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_register_table_firstname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login_table',
        ),
    ]
