# Generated by Django 4.2.5 on 2023-10-09 10:23

import App.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_delete_login_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]{1}[a-z_]{1,20}[0-9]{2,10}', message='Enter a correct username')])),
                ('password', models.CharField(max_length=250, validators=[App.models.validate_password_model])),
            ],
        ),
    ]
