# Generated by Django 4.2.5 on 2023-10-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_login_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_table',
            old_name='username',
            new_name='email',
        ),
    ]
