# Generated by Django 4.2.6 on 2023-10-10 09:12

import App.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_rename_username_login_table_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='email',
            field=models.CharField(max_length=200, validators=[App.models.validate_mail]),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='lastname',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Only alphabets are allowed')]),
        ),
    ]
