# Generated by Django 4.2.6 on 2023-10-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_login_table_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_table',
            name='fullname',
        ),
    ]
