# Generated by Django 4.2.6 on 2023-10-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_login_table_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_table',
            name='fullname',
        ),
        migrations.AddField(
            model_name='register_table',
            name='fullname',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
